config/routes.rb
Rails.application.routes.draw do

  # Root: users#index
  root to: 'users#index'

  # Baker: orders#edit
  get '/Baker', to: 'orders#index', as: 'orders'
  get 'orders/:id', to: 'orders#show', as: 'order'
  get '/orders/:id/edit', to: 'orders#edit', as: 'edit_order'
  patch '/orders/:id', to: 'orders#update'

  # Cashier: orders#new
  get '/Cashier', to: 'orders#new', as: 'new_order'
  post '/orders', to: 'orders#create'

  # Manager: orders#index
  get '/Manager', to: 'users#manager', as: 'manager'

  delete '/orders/:id', to: 'orders#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  attr_accessor :time
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all.order('pickup ASC')
  end

  def new
    @order = Order.new
  end

  def create
    order = Order.new(order_params)
    order.pickup = Time.parse "#{order_params[:time]}"
    order.ready = false

    if order.save
      flash[:notice] = 'Order saved.'
    else
      flash[:error] = 'There was an error in saving the order. Please try again.'
    end

    redirect_to new_order_path
  end

  def show
    @order = Order.find_by_id(params[:id])
  end

  def edit
    @order = Order.find_by_id(params[:id])
  end

  def update
    order = Order.find_by_id(params[:id])
    order.update_attributes(order_params)
    flash[:notice] = 'Order updated.'
    redirect_to orders_path(order)
  end

  def destroy
    order = Order.find_by_id(params[:id])
    order.destroy
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:name, :phone, :time, :size, :toppings, :ready)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def manager
    @orders = Order.all.order('created_at ASC')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_ready(boolean)
    boolean ? 'Yes' : 'No'
  end
  
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.erb
<h1 class="header"><%= link_to "ACME Pizza Company", root_path %></h1>

app/views/application/manager.html.erb
<h2>Manager</h2>
<h3>All Orders</h3>

<table>
  <thead>
    <tr>
      <th>Order Created at</th>
      <th>Pickup</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Size</th>
      <th>Toppings</th>
      <th>Ready for Pickup?</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.created_at %></td>
        <td><%= order.pickup %></td>
        <td><%= order.name %></td>
        <td><%= order.phone %></td>
        <td><%= order.size %></td>
        <td><%= order.toppings %></td>
        <td><%= order.ready %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ACME Pizza Company</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: 'header' %>

    <div>
      <% flash.each do |key, value| %>
        <div class="flash-msg">
          <%= value %>          
        </div>
      <% end %>
    </div>

    <div>
      <%= yield %>
    </div>
  </body>

</html>

app/views/orders/edit.html.erb
<div class="order-form">
  <%= form_for @order do |f| %>
    <% time = @order.pickup[11..15] %>

    <div>
      <%= f.label "Name:", class: "col-form-label" %>
      <%= f.text_field :name, class: "form-control", required: "true", minlength: 1 %>
    </div>
    <div>
      <%= f.label "Phone:", class: "col-form-label" %>
      <%= f.telephone_field :phone, class: "form-control", required: "true", minlength: 10 %>
    </div>
    <div>
      <%= f.label "Pickup Time (Military):", class: "col-form-label" %>
      <%= f.time_field :time, value: time, class: "form-control", required: "true" %>
    </div>
    <div>
      <%= f.label "Size:", class: "col-form-label" %>
      <%= f.select :size, ['Small', 'Medium', 'Large'], class: "form-control" %>
    </div>
    <div>
      <%= f.label "Toppings:", class: "col-form-label" %>
      <%= f.select :toppings, ['Cheese', 'Pepperoni', 'Hawaiian', 'Veggie'], class: "form-control" %>
    </div>
    <div>
      <%= f.label "Ready for Pickup:", class: "col-form-label" %>
      <%= f.select :ready, [['No', false], ['Yes', true]], class: "form-control" %>
    </div>
    <div class="form-btn">
      <%= f.submit "Save Order", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/orders/index.html.erb
<h2>Baker</h2>
<h3>View & Update Order Status</h3>

<table class="table table-striped table-bordered table-sm">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Pickup Time</th>
      <th scope="col">Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Size</th>
      <th scope="col">Toppings</th>
      <th scope="col">Ready for Pickup?</th>
      <th scope="col">Edit Order</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.pickup[5..9] %></td>
        <td><%= order.pickup[11..15] %></td>
        <td><%= order.name %></td>
        <td><%= order.phone.insert(0, '(').insert(4, ') ').insert(9, ' ') %></td>
        <td><%= order.size %></td>
        <td><%= order.toppings %></td>
        <td><%= is_ready(order.ready?) %></td>
        <td><%= link_to "Edit", edit_order_path(order.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h2>Cashier</h2>
<h3>Place a New Order</h3>

<div class="order-form">
  <%= form_for @order, url: "/orders", method: "post" do |f| %>
    <div>
      <%= f.label "Name:", class: "col-form-label" %>
      <%= f.text_field :name, class: "form-control", required: "true", minlength: 1 %>
    </div>
    <div>
      <%= f.label "Phone:", class: "col-form-label" %>
      <%= f.telephone_field :phone, placeholder: "5105554321", class: "form-control", required: "true", minlength: 10 %>
    </div>
    <div>
      <%= f.label "Pickup Time:", class: "col-form-label" %>
      <%= f.time_field :time, class: "form-control", required: "true" %>
    </div>
    <div>
      <%= f.label "Size:", class: "col-form-label" %>
      <%= f.select :size, ['Small', 'Medium', 'Large'], class: "form-control" %>
    </div>
    <div>
      <%= f.label "Toppings:", class: "col-form-label" %>
      <%= f.select :toppings, ['Cheese', 'Pepperoni', 'Hawaiian', 'Veggie'], class: "form-control" %>
    </div>
    <div class="form-btn">
      <%= f.submit "Save Order", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h2>I am a:</h2>

<% @users.each do |user| %>
  <%= button_to "#{user.name}", "/#{user.name}", method: :get, class: "btn btn-light app-user" %>
<% end %>

app/views/users/manager.html.erb
<h2>Manager</h2>
<h3>View Order History</h3>

<table class="table table-striped table-bordered table-sm">
  <thead>
    <tr>
      <th scope="col">Date Created</th>
      <th scope="col">Time Created</th>
      <th scope="col">Pickup Time</th>
      <th scope="col">Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Size</th>
      <th scope="col">Toppings</th>
      <th scope="col">Ready for Pickup?</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.created_at.getlocal.strftime("%m-%d") %></td>
        <td><%= order.created_at.getlocal.strftime("%H:%M") %></td>
        <td><%= order.pickup[11..15] %></td>
        <td><%= order.name %></td>
        <td><%= order.phone.insert(0, '(').insert(4, ') ').insert(9, ' ') %></td>
        <td><%= order.size %></td>
        <td><%= order.toppings %></td>
        <td><%= is_ready(order.ready?) %></td>
      </tr>
    <% end %>
  </tbody>
</table>